version: "3.6"
services:
  app:
    build: .
    image: mlo/app
    volumes:
      - .:/var/www/app:cached
  web:
    image: nginx:alpine
    depends_on:
      - app
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www/app:ro
    ports:
      - 8000:80
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: app
    volumes:
      - dbdata:/var/lib/mysql
  redis:
    image: redis:alpine
  worker:
    image: mlo/app
    command: php artisan horizon
    volumes:
      - .:/var/www/app:cached
  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
volumes:
  dbdata:
